sudo: false
language: node_js
node_js:
  - v5
  - v4
  - '0.12'
  - '0.10'
notifications:
  email: false
services: mongodb
before_install: npm install crypto;npm install -g gulp sequelize-cli
before_script: sequelize db:migrate
install: npm install
after_success: CODECLIMATE_REPO_TOKEN=9338786ef61d320210d94fa289f33d566f3c1a111a38c9e96acdb4c77493d363 codeclimate-test-reporter < coverage/lcov.info
